pipeline:
  identifier: Build_python_webapp_1746801275883
  name: Build python-webapp
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.account_github_connector
        repoName: python-webapp
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: setupvirtualenvironment
                  name: setup virtual environment
                  spec:
                    command: |-
                      python3 -m venv .venv
                      . .venv/bin/activate
                      python3 -m pip install -r requirements.txt
                  timeout: ""
                  type: Run
              - step:
                  type: RunTests
                  name: Run Python Tests
                  identifier: Run_Python_Tests
                  spec:
                    language: Python
                    buildTool: Pytest
                    runOnlySelectedTests: true
                    preCommand: |-
                      python3 -m venv .venv
                      . .venv/bin/activate

                      python3 -m pip install -r requirements/test.txt
              - step:
                  type: RunTests
                  name: RunTests_1
                  identifier: RunTests_1
                  spec:
                    language: Python
                    buildTool: Pytest
                    runOnlySelectedTests: true
                    enableTestSplitting: false
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    connectorRef: dockerhub_connector
                    repo: victorialloyd/python-webapp
                    tags:
                      - <+pipeline.sequenceId>
                    caching: true
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
